//
//  baseViewController.swift
//  English
//
//  Created by 森下大地 on 2020/12/13.
//

import UIKit

//単語と意味をまとめるための関数
struct  WordMeaning{
    let word: String
    let meaning: String
   
    init(word: String, meaning: String) {
        self.word = word
        self.meaning = meaning
    }
    
}

class baseViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
    @IBOutlet weak var baseTableView: UITableView!
    
  
    //単語と意味をまとめている。
    //sectionが設定でき、増やすためには下で設定できる
    let wordmeaning:[[WordMeaning]] = [
        [.init(word: "abandon", meaning: "捨てる"),
         .init(word: "abandon", meaning: "非難する"),
         .init(word: "abandon", meaning: "認める"),
         .init(word: "abandon", meaning: "習得する"),
         .init(word: "abandon", meaning: "適応する"),
         .init(word: "abandon", meaning: "慣れる"),
         .init(word: "abandon", meaning: "感心する/賞賛する"),
         .init(word: "abandon", meaning: "認める"),
         .init(word: "abandon", meaning: "採用する/養子にする"),
         .init(word: "abandon", meaning: "主張する"),
         .init(word: "afford", meaning: "余裕がある"),
         .init(word: "aim", meaning: "ねらう/目指す"),
         .init(word: "alarm", meaning: "怯えさせる"),
         .init(word: "allow", meaning: "許可する"),
         .init(word: "amaze", meaning: "驚嘆させる"),
         .init(word: "amuse", meaning: "楽しませる"),
         .init(word: "apeal", meaning: "＜理性・感情など＞訴える/引きつける"),
         .init(word: "apply", meaning: "当てはまる/申し込む"),
         .init(word: "appoint", meaning: "任命する"),
         .init(word: "approach", meaning: "接近する/取り組む"),
         .init(word: "approve", meaning: "承認する"),
         .init(word: "argue", meaning: "主張する/議論する"),
         .init(word: "arouse", meaning: "刺激する"),
         .init(word: "arrange", meaning: "手はずを整える"),
         .init(word: "arrest", meaning: "逮捕する"),
         .init(word: "assemble", meaning: "組み立てる"),
         .init(word: "assign", meaning: "割り当てる/任命につかせる"),
         .init(word: "associate", meaning: "関連づける/連想させる"),
         .init(word: "assure", meaning: "保証する"),
         .init(word: "astonish", meaning: "驚嘆させる"),
         .init(word: "attach", meaning: "くっつける"),
         .init(word: "attract", meaning: "引きつける/誘惑する"),
         .init(word: "attribute", meaning: "〜のせいにする"),
         .init(word: "ban", meaning: "禁止する"),
         .init(word: "base", meaning: "基づいている"),
         .init(word: "belong", meaning: "所属する"),
         .init(word: "bet", meaning: "きっと〜だと思う"),
         .init(word: "betray", meaning: "裏切る"),
         .init(word: "bind", meaning: "束縛する"),
         .init(word: "blame", meaning: "非難する"),
         .init(word: "bore", meaning: "うんざりさせる"),
         .init(word: "bother", meaning: "面倒をかける/困らせる"),
         .init(word: "bow", meaning: "おじぎする"),
         .init(word: "breed", meaning: "繁殖する"),
         .init(word: "burst", meaning: "破裂する"),
         .init(word: "capture", meaning: "捕らえる"),
         .init(word: "cast", meaning: "投げる/＜目を＞向ける"),
         .init(word: "celebrate", meaning: "祝う"),
         .init(word: "chase", meaning: "追いかける"),
         .init(word: "cheat", meaning: "だます"),
         .init(word: "cheer", meaning: "励ます"),
         .init(word: "cherish", meaning: "胸に抱く"),
         .init(word: "cite", meaning: "引き合いに出す"),
         .init(word: "claim", meaning: "主張する"),
         .init(word: "coincide", meaning: "同時に起きる/重なる"),
         .init(word: "collapse", meaning: "崩壊する"),
         .init(word: "combine", meaning: "結合させる"),
         .init(word: "commit", meaning: "＜罪など＞犯す"),
         .init(word: "commute", meaning: "通勤する"),
         .init(word: "compare", meaning: "比較する"),
         .init(word: "compel", meaning: "強制する"),
         .init(word: "compensate", meaning: "埋め合わせる"),
         .init(word: "compose", meaning: "組み立てる"),
         .init(word: "comprehend", meaning: "理解する"),
         .init(word: "comprise", meaning: "構成させる"),
         .init(word: "conceive", meaning: "想像する/思いつく/考える"),
         .init(word: "concentrate", meaning: "集中する"),
         .init(word: "conclude", meaning: "結論づける"),
         .init(word: "confine", meaning: "限定する/閉じ込める"),
         .init(word: "conform", meaning: "従う"),
         .init(word: "confront", meaning: "立ち向かう"),
         .init(word: "confuse", meaning: "当惑させる"),
         .init(word: "congratulate", meaning: "おめでとうと言う"),
         .init(word: "connect", meaning: "つなぐ/関係づける"),
         .init(word: "consider", meaning: "考慮する"),
         .init(word: "consist", meaning: "構成されている"),
         .init(word: "constitute", meaning: "構成する"),
         .init(word: "consult", meaning: "相談する"),
         .init(word: "continue", meaning: "続ける"),
         .init(word: "contradict", meaning: "矛盾する"),
         .init(word: "contribute", meaning: "貢献する"),
         .init(word: "convert", meaning: "転換する"),
         .init(word: "convince", meaning: "納得させる"),
         .init(word: "correspond", meaning: "一致する"),
         .init(word: "cost", meaning: "＜費用を＞要する"),
         .init(word: "crash", meaning: "衝突する"),
         .init(word: "crush", meaning: "押しつぶす"),
         .init(word: "cultivate", meaning: "育む/耕作する"),
         .init(word: "cure", meaning: "治療する"),
         .init(word: "dare", meaning: "〜する勇気がある"),
         .init(word: "decide", meaning: "決意する/決定する"),
         .init(word: "decline", meaning: "低下する/辞退する"),
         .init(word: "decorate", meaning: "装飾する"),
         .init(word: "dedicate", meaning: "ささげる"),
         .init(word: "delay", meaning: "遅らせる"),
         .init(word: "deliver", meaning: "配達する"),
         .init(word: "demand", meaning: "要求する"),
         .init(word: "demonstrate", meaning: "証明する/明らかに示す"),
         .init(word: "depend", meaning: "依存する"),
         .init(word: "depress", meaning: "憂鬱にさせる"),
         .init(word: "deprive", meaning: "奪う"),
         .init(word: "derive", meaning: "由来する"),
         .init(word: "descend", meaning: "降りる/＜先祖から＞伝わる"),
         .init(word: "describe", meaning: "描写する"),
         .init(word: "designate", meaning: "指定する"),
         .init(word: "destroy", meaning: "破壊する"),
         .init(word: "detect", meaning: "探知する/発見する"),
         .init(word: "devastate", meaning: "壊滅させる"),
         .init(word: "develop", meaning: "発達する"),
         .init(word: "devote", meaning: "ささげる"),
         .init(word: "dictate", meaning: "命じる/要求する/決定する"),
         .init(word: "digest", meaning: "消化する"),
         .init(word: "diminish", meaning: "減少する/衰える"),
         .init(word: "disappoint", meaning: "失望させる"),
         .init(word: "dismiss", meaning: "無視する/退ける"),
         .init(word: "displace", meaning: "故郷から追い出す"),
         .init(word: "display", meaning: "展示する"),
         .init(word: "dissolve", meaning: "溶解する/解放する"),
         .init(word: "disturb", meaning: "妨げる/邪魔をする"),
         .init(word: "donate", meaning: "提供する"),
         .init(word: "draw", meaning: "引っ張る/描く"),
         .init(word: "drown", meaning: "溺れ死ぬ"),
         .init(word: "earn", meaning: "もうける/稼ぐ"),
         .init(word: "elect", meaning: "選挙で選ぶ"),
         .init(word: "embarrass", meaning: "困惑させる/恥ずかしい思いをさせる"),
         .init(word: "embrace", meaning: "＜思想など＞受け入れる/含む"),
         .init(word: "emerge", meaning: "現れる"),
         .init(word: "employ", meaning: "雇う"),
         .init(word: "enclose", meaning: "囲む"),
         .init(word: "encounter", meaning: "偶然出会う/遭遇する"),
         .init(word: "encourage", meaning: "励ます"),
         .init(word: "endanger", meaning: "危険にさらす"),
         .init(word: "enforce", meaning: "施行する"),
         .init(word: "engage", meaning: "従事する"),
         .init(word: "enter", meaning: "入る/記入する"),
         .init(word: "envy", meaning: "うらやむ"),
         .init(word: "equip", meaning: "装備させる/準備させる"),
         .init(word: "escape", meaning: "逃げる"),
         .init(word: "establish", meaning: "確立する/設立する"),
         .init(word: "estimate", meaning: "推定する"),
         .init(word: "examine", meaning: "調査する"),
         .init(word: "exhaust", meaning: "疲れ果てさせる"),
         .init(word: "exhibit", meaning: "展示する"),
         .init(word: "expand", meaning: "拡大する"),
         .init(word: "expect", meaning: "予期する"),
         .init(word: "exploit", meaning: "利用する/開発する"),
         .init(word: "expose", meaning: "さらす"),
         .init(word: "extend", meaning: "広げる/延長する"),
         .init(word: "fascinate", meaning: "夢中にさせる"),
         .init(word: "feed", meaning: "エサをやる"),
         .init(word: "focus", meaning: "焦点を合わせる"),
         .init(word: "follow", meaning: "続く/従う"),
         .init(word: "force", meaning: "強制する"),
         .init(word: "forgive", meaning: "＜人を＞許す"),
         .init(word: "foster", meaning: "促進する/育成する"),
         .init(word: "found", meaning: "設立する"),
         .init(word: "freeze", meaning: "凍りつく"),
         .init(word: "frighten", meaning: "怯えさせる"),
         .init(word: "frustrate", meaning: "欲求不満にさせる/いらだたせる"),
         .init(word: "fulfill", meaning: "果たす"),
         .init(word: "gain", meaning: "得る"),
         .init(word: "graduate", meaning: "卒業する"),
         .init(word: "grant", meaning: "認める/与える"),
         .init(word: "grasp", meaning: "理解する"),
         .init(word: "hatch", meaning: "＜卵など＞かえす"),
         .init(word: "heal", meaning: "治す"),
         .init(word: "hire", meaning: "雇う"),
         .init(word: "hurt", meaning: "傷つける"),
         .init(word: "identify", meaning: "正体をつきとめる/確認する"),
         .init(word: "illuminate", meaning: "照らす/解明する"),
         .init(word: "illustrate", meaning: "示す/説明する"),
         .init(word: "implement", meaning: "実行する"),
         .init(word: "imply", meaning: "ほのめかす"),
         .init(word: "import", meaning: "輸入する"),
         .init(word: "impose", meaning: "課す/押しつける"),
         .init(word: "improve", meaning: "向上させる"),
         .init(word: "include", meaning: "含む"),
         .init(word: "increase", meaning: "増える"),
         .init(word: "indicate", meaning: "指し示す"),
         .init(word: "induce", meaning: "誘う/引き起こす"),
         .init(word: "indulge", meaning: "＜快楽など＞ふける"),
         .init(word: "infect", meaning: "感染する"),
         .init(word: "injure", meaning: "傷つける/怪我をさせる"),
         .init(word: "insist", meaning: "主張する/言い張る"),
         .init(word: "inspire", meaning: "やる気にさせる"),
         .init(word: "interfere", meaning: "邪魔をする"),
         .init(word: "interrupt", meaning: "妨げる/中断する"),
         .init(word: "introduce", meaning: "紹介する"),
         .init(word: "invest", meaning: "投資する"),
         .init(word: "irritate", meaning: "苛立たせる"),
         .init(word: "join", meaning: "参加する"),
         .init(word: "judge", meaning: "判断する"),
         .init(word: "launch", meaning: "始める"),
         .init(word: "leak", meaning: "漏らす"),
         .init(word: "lean", meaning: "寄りかかる"),
         .init(word: "locate", meaning: "位置する"),
         .init(word: "manufacture", meaning: "製造する"),
         .init(word: "match", meaning: "匹敵する/調和する"),
         .init(word: "mention", meaning: "述べる"),
         .init(word: "mistake", meaning: "誤解する"),
         .init(word: "mount", meaning: "すえつける/乗る"),
         .init(word: "multiply", meaning: "増やす/増える"),
         .init(word: "neglect", meaning: "無視する"),
         .init(word: "negotiate", meaning: "交渉する"),
         .init(word: "nod", meaning: "うなずく"),
         .init(word: "notice", meaning: "気づく"),
         .init(word: "oblige", meaning: "強いる"),
         .init(word: "occupy", meaning: "占める"),
         .init(word: "offer", meaning: "申し出る"),
         .init(word: "operate", meaning: "作動する/操作する"),
         .init(word: "oppress", meaning: "しいたげる"),
         .init(word: "overlook", meaning: "見落とす"),
         .init(word: "owe", meaning: "おかげ"),
         .init(word: "own", meaning: "所有している"),
         .init(word: "pardon", meaning: "許す"),
         .init(word: "participate", meaning: "参加する"),
         .init(word: "penetrate", meaning: "入り込む/貫通する"),
         .init(word: "perceive", meaning: "知覚する/気づく"),
         .init(word: "perform", meaning: "行う/遂行する"),
         .init(word: "persist", meaning: "維持する"),
         .init(word: "persuade", meaning: "説得する"),
         .init(word: "plunge", meaning: "突っ込む"),
         .init(word: "precede", meaning: "先行する/先立つ"),
         .init(word: "prefer", meaning: "〜をより好む"),
         .init(word: "prepare", meaning: "準備をする"),
         .init(word: "prescribe", meaning: "処方する"),
         .init(word: "preserve", meaning: "保護する"),
         .init(word: "presume", meaning: "推定する"),
         .init(word: "prevail", meaning: "普及している/広まる"),
         .init(word: "prevent", meaning: "妨げる"),
         .init(word: "prohibit", meaning: "禁じる"),
         .init(word: "prompt", meaning: "促す"),
         .init(word: "pronounce", meaning: "発音する"),
         .init(word: "prove", meaning: "証明する"),
         .init(word: "provide", meaning: "供給する/与える"),
         .init(word: "provoke", meaning: "引き起こす")],
        
        [.init(word: "abuse", meaning: "虐待"),
         .init(word: "access", meaning: "利用する権利"),
         .init(word: "acquaintance", meaning: "知人"),
         .init(word: "administration", meaning: "経営/行政"),
         .init(word: "advance", meaning: "前進/進歩"),
         .init(word: "agency", meaning: "代理店/機関"),
         .init(word: "ally", meaning: "同盟国"),
         .init(word: "alternative", meaning: "代わりになるもの"),
         .init(word: "appearance", meaning: "外見/様子"),
         .init(word: "appointment", meaning: "約束/予約"),
         .init(word: "asset", meaning: "財産"),
         .init(word: "atmosphere", meaning: "大気/雰囲気"),
         .init(word: "attempt", meaning: "試み"),
         .init(word: "audience", meaning: "聴衆"),
         .init(word: "award", meaning: "賞"),
         .init(word: "background", meaning: "背景"),
         .init(word: "basis", meaning: "基礎/根拠"),
         .init(word: "benefit", meaning: "利益"),
         .init(word: "blessing", meaning: "ありがたいもの"),
         .init(word: "border", meaning: "国境地帯/境界"),
         .init(word: "branch", meaning: "枝/支店"),
         .init(word: "breakdown", meaning: "崩壊"),
         .init(word: "burden", meaning: "重荷"),
         .init(word: "canal", meaning: "運河"),
         .init(word: "capacity", meaning: "能力"),
         .init(word: "caution", meaning: "用心/ 警告"),
         .init(word: "characteristic", meaning: "特徴"),
         .init(word: "charm", meaning: "魅力"),
         .init(word: "circulation", meaning: "循環/発行部数"),
         .init(word: "client", meaning: "依頼人"),
         .init(word: "climate", meaning: "気候"),
         .init(word: "compound", meaning: "化合物"),
         .init(word: "conflict", meaning: "対立/紛争"),
         .init(word: "constitution", meaning: "憲法"),
         .init(word: "context", meaning: "文脈/状況"),
         .init(word: "contract", meaning: "契約"),
         .init(word: "convention", meaning: "慣習"),
         .init(word: "core", meaning: "中心/核心"),
         .init(word: "counterpart", meaning: "〜に相当するもの"),
         .init(word: "craft", meaning: "工芸"),
         .init(word: "curse", meaning: "呪い"),
         .init(word: "custom", meaning: "習慣"),
         .init(word: "dawn", meaning: "夜明け"),
         .init(word: "delight", meaning: "大喜び"),
         .init(word: "democracy", meaning: "民主主義"),
         .init(word: "department", meaning: "部門/学科"),
         .init(word: "deposit", meaning: "預金/頭金"),
         .init(word: "desert", meaning: "砂漠"),
         .init(word: "dimension", meaning: "側面/要素"),
         .init(word: "disability", meaning: "障害"),
         .init(word: "disgust", meaning: "嫌悪"),
         .init(word: "distress", meaning: "苦しみ"),
         .init(word: "divorce", meaning: "離婚"),
         .init(word: "draft", meaning: "下書き/徴兵"),
         .init(word: "duty", meaning: "義務"),
         .init(word: "economy", meaning: "経済"),
         .init(word: "effect", meaning: "効果/影響"),
         .init(word: "element", meaning: "要素"),
         .init(word: "emergency", meaning: "緊急事態"),
         .init(word: "endeavor", meaning: "活動"),
         .init(word: "enterprise", meaning: "企業/事業"),
         .init(word: "enthusiasm", meaning: "熱意/情熱"),
         .init(word: "equivalent", meaning: "同等のもの"),
         .init(word: "ethic", meaning: "倫理"),
         .init(word: "excuse", meaning: "言い訳"),
         .init(word: "experience", meaning: "体験/経験"),
         .init(word: "fabric", meaning: "織物/布/組織"),
         .init(word: "facility", meaning: "施設"),
         .init(word: "faculity", meaning: "学部/能力"),
         .init(word: "faith", meaning: "信頼"),
         .init(word: "favor", meaning: "好意"),
         .init(word: "feature", meaning: "特徴"),
         .init(word: "fee", meaning: "料金"),
         .init(word: "flock", meaning: "群れ"),
         .init(word: "flood", meaning: "洪水"),
         .init(word: "formula", meaning: "方法/解決策"),
         .init(word: "frame", meaning: "枠"),
         .init(word: "frontier", meaning: "国境"),
         .init(word: "grade", meaning: "学年/成績"),
         .init(word: "grain", meaning: "穀物"),
         .init(word: "gravity", meaning: "重力"),
         .init(word: "harm", meaning: "害"),
         .init(word: "haste", meaning: "急ぐこと"),
         .init(word: "height", meaning: "高さ"),
         .init(word: "honor", meaning: "名誉"),
         .init(word: "horizon", meaning: "地平線"),
         .init(word: "immigrant", meaning: "移民"),
         .init(word: "impact", meaning: "影響"),
         .init(word: "individual", meaning: "個人"),
         .init(word: "industry", meaning: "工業"),
         .init(word: "influence", meaning: "影響"),
         .init(word: "initiative", meaning: "主導権"),
         .init(word: "inquiry", meaning: "調査"),
         .init(word: "institution", meaning: "機関/制度"),
         .init(word: "interaction", meaning: "交流"),
         .init(word: "jam", meaning: "渋滞"),
         .init(word: "junk", meaning: "くず/ガラクタ"),
         .init(word: "kid", meaning: "子供"),
         .init(word: "kingdom", meaning: "王国"),
         .init(word: "lag", meaning: "遅れ"),
         .init(word: "laughter", meaning: "笑い"),
         .init(word: "load", meaning: "荷物"),
         .init(word: "lord", meaning: "神/領主"),
         .init(word: "mass", meaning: "一般大衆"),
         .init(word: "material", meaning: "物質/材料"),
         .init(word: "medium", meaning: "手段"),
         .init(word: "mercy", meaning: "慈悲"),
         .init(word: "mine", meaning: "鉱山"),
         .init(word: "minister", meaning: "大臣"),
         .init(word: "mission", meaning: "使命/任務"),
         .init(word: "nap", meaning: "うたた寝"),
         .init(word: "neighbor", meaning: "隣人"),
         .init(word: "norm", meaning: "規範"),
         .init(word: "objective", meaning: "目的/目標"),
         .init(word: "occasion", meaning: "場合"),
         .init(word: "occupation", meaning: "職業"),
         .init(word: "officer", meaning: "役人"),
         .init(word: "official", meaning: "役人"),
         .init(word: "organ", meaning: "臓器"),
         .init(word: "outlook", meaning: "考え方/見通し"),
         .init(word: "output", meaning: "生産高/アウトプット"),
         .init(word: "pain", meaning: "苦痛"),
         .init(word: "paradox", meaning: "逆説"),
         .init(word: "parallel", meaning: "類似/ 匹敵するもの"),
         .init(word: "passage", meaning: "一節/経過"),
         .init(word: "patient", meaning: "患者"),
         .init(word: "peer", meaning: "同僚"),
         .init(word: "perspective", meaning: "見方"),
         .init(word: "pile", meaning: "積み重ね"),
         .init(word: "pill", meaning: "錠剤"),
         .init(word: "plague", meaning: "疫病"),
         .init(word: "plot", meaning: "（小説など）筋/陰謀"),
         .init(word: "poison", meaning: "毒"),
         .init(word: "pole", meaning: "棒/北極・南極"),
         .init(word: "poll", meaning: "世論調査/投票"),
         .init(word: "prejudice", meaning: "偏見"),
         .init(word: "premise", meaning: "前提"),
         .init(word: "prey", meaning: "獲物"),
         .init(word: "principle", meaning: "原理/原則"),
         .init(word: "progress", meaning: "進歩"),
         .init(word: "project", meaning: "計画"),
         .init(word: "property", meaning: "財産"),
         .init(word: "proportion", meaning: "比率"),
         .init(word: "Protest", meaning: "抗議"),
         .init(word: "publicity", meaning: "宣伝"),
         .init(word: "quanity", meaning: "量"),
         .init(word: "quater", meaning: "4分の1"),
         .init(word: "rage", meaning: "激怒"),
         .init(word: "range", meaning: "範囲"),
         .init(word: "rank", meaning: "地位/階級"),
         .init(word: "rate", meaning: "割合/速度"),
         .init(word: "reception", meaning: "もてなし"),
         .init(word: "recession", meaning: "不景気"),
         .init(word: "region", meaning: "地域"),
         .init(word: "relative", meaning: "親族/親戚"),
         .init(word: "resident", meaning: "住民"),
         .init(word: "result", meaning: "結果"),
         .init(word: "review", meaning: "再検討/復習"),
         .init(word: "revolution", meaning: "革命"),
         .init(word: "reward", meaning: "報酬"),
         .init(word: "risk", meaning: "危険"),
         .init(word: "routine", meaning: "日課"),
         .init(word: "row", meaning: "列"),
         .init(word: "scene", meaning: "場面/現場"),
         .init(word: "scope", meaning: "範囲"),
         .init(word: "security", meaning: "安全"),
         .init(word: "sensation", meaning: "感覚"),
         .init(word: "sequence", meaning: "連続/順番"),
         .init(word: "service", meaning: "公共事業/サービス"),
         .init(word: "session", meaning: "期間/討論"),
         .init(word: "shade", meaning: "陰"),
         .init(word: "shelter", meaning: "避難所"),
         .init(word: "sight", meaning: "みること/光景"),
         .init(word: "sign", meaning: "印/兆候"),
         .init(word: "slave", meaning: "奴隷"),
         .init(word: "society", meaning: "社会"),
         .init(word: "span", meaning: "期間"),
         .init(word: "spectacle", meaning: "光景/見せ物"),
         .init(word: "sphere", meaning: "領域/範囲"),
         .init(word: "spirit", meaning: "精神"),
         .init(word: "square", meaning: "正方形"),
         .init(word: "statistics", meaning: "統計"),
         .init(word: "stereotype", meaning: "固定観念"),
         .init(word: "stock", meaning: "株/貯蔵品"),
         .init(word: "strain", meaning: "負担"),
         .init(word: "strip", meaning: "細長い一片"),
         .init(word: "stroke", meaning: "発作/打撃"),
         .init(word: "stuff", meaning: "物/材料"),
         .init(word: "sum", meaning: "金額/合計"),
         .init(word: "summit", meaning: "頂点/首脳会議"),
         .init(word: "taste", meaning: "味"),
         .init(word: "temper", meaning: "気性/気分"),
         .init(word: "terminal", meaning: "終点"),
         .init(word: "territory", meaning: "領土"),
         .init(word: "therapy", meaning: "治療"),
         .init(word: "tide", meaning: "潮流"),
         .init(word: "tissue", meaning: "組織"),
         .init(word: "track", meaning: "足跡"),
         .init(word: "trade", meaning: "貿易"),
         .init(word: "traffic", meaning: "交通"),
         .init(word: "transport", meaning: "交通機関/輸送"),
         .init(word: "trap", meaning: "わな"),
         .init(word: "treasure", meaning: "財宝"),
         .init(word: "trend", meaning: "傾向/流行"),
         .init(word: "trial", meaning: "試み"),
         .init(word: "trouble", meaning: "悩み"),
         .init(word: "tune", meaning: "曲"),
         .init(word: "value", meaning: "価値"),
         .init(word: "vehicle", meaning: "車/乗り物"),
         .init(word: "venture", meaning: "冒険"),
         .init(word: "version", meaning: "型"),
         .init(word: "vessel", meaning: "船/血管"),
         .init(word: "volunteer", meaning: "ボランティア"),
         .init(word: "vote", meaning: "投票"),
         .init(word: "welfare", meaning: "福祉"),
         .init(word: "wheel", meaning: "車輪"),
         .init(word: "witness", meaning: "証人/目撃者"),
         .init(word: "worship", meaning: "崇拝"),
         .init(word: "wound", meaning: "けが")],
        
        [.init(word: "accordingly", meaning: "それ相応に"),
         .init(word: "accustomed", meaning: "慣れた"),
         .init(word: "actually", meaning: "実は"),
         .init(word: "acute", meaning: "深刻な"),
         .init(word: "aged", meaning: "年老いた"),
         .init(word: "alien", meaning: "外国の/異質な"),
         .init(word: "alike", meaning: "似ている"),
         .init(word: "altogether", meaning: "完全に"),
         .init(word: "annual", meaning: "年に一度の/一年間の"),
         .init(word: "anxious", meaning: "心配して/不安な"),
         .init(word: "apt", meaning: "〜しがちである"),
         .init(word: "available", meaning: "利用可能な"),
         .init(word: "awake", meaning: "目を覚まして"),
         .init(word: "awful", meaning: "ひどい"),
         .init(word: "awkward", meaning: "気まずい"),
         .init(word: "barely", meaning: "かろうじて"),
         .init(word: "beneath", meaning: "〜の下で"),
         .init(word: "besides", meaning: "〜に加えて"),
         .init(word: "bitter", meaning: "苦い/腹を立てた"),
         .init(word: "brilliant", meaning: "素晴らしい"),
         .init(word: "calm", meaning: "冷静な"),
         .init(word: "capable", meaning: "〜する能力がある"),
         .init(word: "casual", meaning: "気楽な/形式ばらない"),
         .init(word: "chemical", meaning: "化学的な"),
         .init(word: "civil", meaning: "一般市民の"),
         .init(word: "classical", meaning: "クラシックの/古典的な"),
         .init(word: "common", meaning: "共通の/普通の"),
         .init(word: "complex", meaning: "複雑な"),
         .init(word: "concrete", meaning: "具体的な"),
         .init(word: "conscious", meaning: "意識している"),
         .init(word: "consistent", meaning: "矛盾のない/一致した"),
         .init(word: "contemporary", meaning: "現在の"),
         .init(word: "contrary", meaning: "反対に"),
         .init(word: "correct", meaning: "正しい"),
         .init(word: "crude", meaning: "粗末な"),
         .init(word: "curious", meaning: "好奇心が強い/奇妙な"),
         .init(word: "current", meaning: "最新の"),
         .init(word: "decent", meaning: "まともな"),
         .init(word: "deliberately", meaning: "わざと"),
         .init(word: "delicate", meaning: "繊細な"),
         .init(word: "desperate", meaning: "必死の"),
         .init(word: "domestic", meaning: "家庭内の/国内の"),
         .init(word: "dull", meaning: "退屈させる"),
         .init(word: "eager", meaning: "熱心な"),
         .init(word: "efficient", meaning: "効率的な"),
         .init(word: "entitled", meaning: "〜をする権利がある"),
         .init(word: "equal", meaning: "平等な"),
         .init(word: "ethnic", meaning: "民族的な"),
         .init(word: "evil", meaning: "悪い"),
         .init(word: "exactly", meaning: "正確に/その通りです"),
         .init(word: "faint", meaning: "かすかな"),
         .init(word: "familiar", meaning: "よく知られた"),
         .init(word: "fierce", meaning: "激しい"),
         .init(word: "fond", meaning: "〜が好き"),
         .init(word: "former", meaning: "前の"),
         .init(word: "fundamental", meaning: "基本的な"),
         .init(word: "genuine", meaning: "本物の"),
         .init(word: "global", meaning: "世界的な"),
         .init(word: "guilty", meaning: "有罪の"),
         .init(word: "humble", meaning: "謙虚な"),
         .init(word: "idele", meaning: "何もしてない/怠け者の"),
         .init(word: "inclined", meaning: "〜する傾向がある"),
         .init(word: "independent", meaning: "独立した"),
         .init(word: "inner", meaning: "内側の"),
         .init(word: "innocent", meaning: "無罪の"),
         .init(word: "intent", meaning: "没頭した"),
         .init(word: "internal", meaning: "内部の/国内の"),
         .init(word: "intimate", meaning: "親密な"),
         .init(word: "involved", meaning: "〜に関係している"),
         .init(word: "jealous", meaning: "羨ましい"),
         .init(word: "keen", meaning: "鋭い"),
         .init(word: "lately", meaning: "最近"),
         .init(word: "latter", meaning: "後者の"),
         .init(word: "legal", meaning: "合法の/法律の"),
         .init(word: "liable", meaning: "〜しがちである"),
         .init(word: "lilely", meaning: "ありそうな/可能性がある"),
         .init(word: "local", meaning: "その土地の"),
         .init(word: "loose", meaning: "ゆるい/自由の"),
         .init(word: "male", meaning: "男の"),
         .init(word: "marvelous", meaning: "驚くべき"),
         .init(word: "mature", meaning: "成熟した"),
         .init(word: "meanwhile", meaning: "その間に"),
         .init(word: "minimum", meaning: "最小限の"),
         .init(word: "miserable", meaning: "惨めな"),
         .init(word: "misleading", meaning: "まぎらわしい"),
         .init(word: "modest", meaning: "控えめな/わずかな"),
         .init(word: "moral", meaning: "道徳的な"),
         .init(word: "Muslim", meaning: "イスラム教の"),
         .init(word: "narrow", meaning: "狭い"),
         .init(word: "native", meaning: "母国の"),
         .init(word: "nearly", meaning: "ほとんど"),
         .init(word: "negative", meaning: "否定の"),
         .init(word: "nervous", meaning: "神経質な/不安な"),
         .init(word: "noble", meaning: "高貴な"),
         .init(word: "nuclear", meaning: "核の/原子力の"),
         .init(word: "obscure", meaning: "わかりにくい"),
         .init(word: "obvious", meaning: "明白な"),
         .init(word: "occasionally", meaning: "時々"),
         .init(word: "overall", meaning: "全面的な/全体的な"),
         .init(word: "particular", meaning: "ある特定の/特有の"),
         .init(word: "passive", meaning: "受動的な"),
         .init(word: "peculiar", meaning: "独特の"),
         .init(word: "plain", meaning: "明白な"),
         .init(word: "pleasant", meaning: "楽しい"),
         .init(word: "positive", meaning: "積極的な"),
         .init(word: "possibly", meaning: "もしかしたら"),
         .init(word: "precisely", meaning: "まさに"),
         .init(word: "pregnant", meaning: "妊娠している"),
         .init(word: "previous", meaning: "前の"),
         .init(word: "prime", meaning: "主要な"),
         .init(word: "private", meaning: "個人の"),
         .init(word: "proper", meaning: "適切な"),
         .init(word: "public", meaning: "公の"),
         .init(word: "pyisical", meaning: "身体の/肉体の"),
         .init(word: "ready", meaning: "用意ができた"),
         .init(word: "reasonable", meaning: "理にかなった"),
         .init(word: "refreshing", meaning: "さわやかな"),
         .init(word: "relevant", meaning: "関連のある"),
         .init(word: "remarkable", meaning: "素晴らしい"),
         .init(word: "rough", meaning: "荒い/大雑把な"),
         .init(word: "scarcely", meaning: "ほとんど〜ない"),
         .init(word: "seldom", meaning: "めったに〜ない"),
         .init(word: "senior", meaning: "上級の/先輩の"),
         .init(word: "serious", meaning: "深刻な"),
         .init(word: "significant", meaning: "重要な"),
         .init(word: "somehow", meaning: "どういうわけか"),
         .init(word: "sophisticated", meaning: "高度な"),
         .init(word: "specific", meaning: "特定の"),
         .init(word: "steady", meaning: "安定の"),
         .init(word: "stiff", meaning: "堅苦しい"),
         .init(word: "substantial", meaning: "たくさんの/実質的な"),
         .init(word: "superior", meaning: "より優れている"),
         .init(word: "tame", meaning: "飼い慣らされた"),
         .init(word: "therefore", meaning: "それゆえ"),
         .init(word: "thin", meaning: "薄い"),
         .init(word: "thrilled", meaning: "ワクワクしている"),
         .init(word: "thus", meaning: "したがって"),
         .init(word: "tight", meaning: "引き締まった/きつい"),
         .init(word: "tough", meaning: "たくましい"),
         .init(word: "underlying", meaning: "根本的な"),
         .init(word: "upset", meaning: "動揺している"),
         .init(word: "vain", meaning: "無駄な"),
         .init(word: "valid", meaning: "妥当な/有効な"),
         .init(word: "vital", meaning: "重要な"),
         .init(word: "vivid", meaning: "鮮やかな"),
         .init(word: "whereas", meaning: "〜だが一方"),
         .init(word: "willing", meaning: "〜する気がある"),
         .init(word: "worth", meaning: "〜の価値がある")],
    ]
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        baseTableView.delegate = self
        baseTableView.dataSource = self
        
        
    }
    
    // データの数（＝セルの数）を返すメソッド
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        
        //ここでしっかりと多次元配列の中身を表示できるようにする。
        return wordmeaning[section].count
    }
    
    // 各セルの内容を返すメソッド
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        // 再利用可能な cell を得る
        let cell = tableView.dequeueReusableCell(withIdentifier: "tableCell", for: indexPath)
        
       
        
        //cellのlableにタグをつけて表示する
        //wordLableは英単語のこと
        //meaningは英単語の意味
        //arrayの中から単語と意味が一緒に出てくるようになっている
        let base1 = cell.viewWithTag(1) as! UILabel
        base1.text = wordmeaning[indexPath.section][indexPath.row].word
        
        
        let base2 = cell.viewWithTag(2) as! UILabel
        base2.text = wordmeaning[indexPath.section][indexPath.row].meaning
        
        
        
        
        return cell
    }
    
    // Cell の高さを１２０にする
      func tableView(_ table: UITableView,
                     heightForRowAt indexPath: IndexPath) -> CGFloat {
          return 120.0
      }
    //section設定
    func numberOfSections(in tableView: UITableView) -> Int {
        return wordmeaning.count
    }
    //sectionのテキスト表示の設定
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let label = UILabel()
        label.text = "level1"
        label.textAlignment = .center
        label.backgroundColor = .green
        
        //sectionの数とタイトルを設定できる
        switch section {
        case 0:
            label.text = "動詞"
        case 1:
            label.text = "名詞"
        case 2:
            label.text = "形容詞"
        default:
            break
        }
        return label
    }
    //sectionの高さの設定
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 50
    }
    
    
}

